version: "3.9"

services:
  app:
    image: ghcr.io/aaafasf/proyecto2:1.0.5
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Dominio (tu segundo apellido)
        - "traefik.http.routers.cuzco.rule=Host(`cuzco.byronrm.com`)"
        - "traefik.http.routers.cuzco.entrypoints=websecure"
        - "traefik.http.routers.cuzco.tls.certresolver=myresolver"

        # Puerto INTERNO DEL CONTENEDOR (CAMBIADO A 1003)
        - "traefik.http.services.cuzco.loadbalancer.server.port=1003"

        # Red que usa Traefik
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
